# Databricks notebook source
# MAGIC %md-sandbox
# MAGIC
# MAGIC # 1/ Ingesting and preparing PDF for LLM and Self Managed Vector Search Embeddings
# MAGIC
# MAGIC ## In this example, we will focus on ingesting pdf documents as source for our retrieval process. 
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/rag-pdf-self-managed-0.png?raw=true" style="float: right; width: 600px; margin-left: 10px">
# MAGIC
# MAGIC
# MAGIC For this example, we will add Databricks ebook PDFs from [Databricks resources page](https://www.databricks.com/resources) to our knowledge database.
# MAGIC
# MAGIC **Note: This demo is advanced content, we strongly recommend going over the simple version first to learn the basics.**
# MAGIC
# MAGIC Here are all the detailed steps:
# MAGIC
# MAGIC - Use autoloader to load the binary PDFs into our first table. 
# MAGIC - Use the `unstructured` library  to parse the text content of the PDFs.
# MAGIC - Use `llama_index` or `Langchain` to split the texts into chuncks.
# MAGIC - Compute embeddings for the chunks.
# MAGIC - Save our text chunks + embeddings in a Delta Lake table, ready for Vector Search indexing.
# MAGIC
# MAGIC
# MAGIC Lakehouse AI not only provides state of the art solutions to accelerate your AI and LLM projects, but also to accelerate data ingestion and preparation at scale, including unstructured data like PDFs.
# MAGIC
# MAGIC <!-- Collect usage data (view). Remove it to disable collection or disable tracker during installation. View README for more details.  -->
# MAGIC <img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=data-science&org_id=5890053377436761&notebook=%2F02-advanced%2F01-PDF-Advanced-Data-Preparation&demo_name=llm-rag-chatbot&event=VIEW&path=%2F_dbdemos%2Fdata-science%2Fllm-rag-chatbot%2F02-advanced%2F01-PDF-Advanced-Data-Preparation&version=1">

# COMMAND ----------

# MAGIC %md 
# MAGIC ### A cluster has been created for this demo
# MAGIC To run this demo, just select the cluster `dbdemos-llm-rag-chatbot-callum_elder` from the dropdown menu ([open cluster configuration](https://adb-5890053377436761.1.azuredatabricks.net/#setting/clusters/0315-001658-1toyiaqo/configuration)). <br />
# MAGIC *Note: If the cluster was deleted after 30 days, you can re-create it with `dbdemos.create_cluster('llm-rag-chatbot')` or re-install the demo: `dbdemos.install('llm-rag-chatbot')`*

# COMMAND ----------

# DBTITLE 1,Install required external libraries 
# MAGIC %pip install transformers==4.30.2 "unstructured[pdf,docx]==0.10.30" langchain==0.1.5 llama-index==0.9.3 databricks-vectorsearch==0.22 pydantic==1.10.9 mlflow==2.10.1 PyPDF2 azure-identity azure-storage-queue azure-storage-blob "unstructured[pptx]" unstructured poppler-utils pdf2image pdfminer.six
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ../_resources/00-init-advanced $reset_all_data=False

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC ## Ingesting Databricks ebook PDFs and extracting their pages
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/rag-pdf-self-managed-1.png?raw=true" style="float: right" width="500px">
# MAGIC
# MAGIC First, let's ingest our PDFs as a Delta Lake table with path urls and content in binary format. 
# MAGIC
# MAGIC We'll use [Databricks Autoloader](https://docs.databricks.com/en/ingestion/auto-loader/index.html) to incrementally ingeset new files, making it easy to incrementally consume billions of files from the data lake in various data formats. Autoloader easily ingests our unstructured PDF data in binary format.
# MAGIC

# COMMAND ----------

# DBTITLE 1,Our pdf or docx files are available in our Volume (or DBFS)
# MAGIC %sql
# MAGIC --Note that we need to enable Change Data Feed on the table to create the index, need to provide catalog name and schema name
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS main.rag_chatbot_callum_elder.500_25_experimental (
# MAGIC   id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC   url STRING,
# MAGIC   basename STRING,
# MAGIC   content STRING,
# MAGIC   bge_embedding ARRAY <FLOAT>,
# MAGIC   ada_embedding ARRAY <FLOAT>,
# MAGIC   openai_large_embedding ARRAY <FLOAT>
# MAGIC ) TBLPROPERTIES (delta.enableChangeDataFeed = true); 
# MAGIC
# MAGIC DESCRIBE DETAIL main.rag_chatbot_callum_elder.500_25_experimental

# COMMAND ----------

# DBTITLE 1,Ingesting PDF files as binary format using Databricks cloudFiles (Autoloader)
#transform pdf to text

from unstructured.partition.auto import partition
import re

# iteration: if pdf is encrypted return empty string
from pdfminer.pdfdocument import PDFEncryptionError

def extract_doc_text(x: bytes) -> str:
    try:
        # Read files and extract the values with unstructured
        sections = partition(file=io.BytesIO(x))

        def clean_section(txt):
            txt = re.sub(r'\n', '', txt)
            return re.sub(r' ?\.', '.', txt)

        # Default split is by section of document, concatenate them all together because we want to split by sentence instead.
        return "\n".join([clean_section(s.text) for s in sections])

    except PDFEncryptionError as e:
        print(f"Skipping encrypted PDF file")
        print(f"Error details: {str(e)}")
        return ""  # Return an empty string or handle the error as needed

    except ValueError as e:
        print(f"Skipping unsupported file format")
        print(f"Error details: {str(e)}")
        return ""

# COMMAND ----------

# test pdf to text function

import io
import re
import requests

with requests.get('https://github.com/databricks-demos/dbdemos-dataset/blob/main/llm/databricks-pdf-documentation/Databricks-Customer-360-ebook-Final.pdf?raw=true') as pdf:
  doc = extract_doc_text(pdf.content)  
  print(doc)

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/rag-pdf-self-managed-2.png?raw=true" style="float: right" width="500px">
# MAGIC
# MAGIC ## Extracting our PDF content as text chunks
# MAGIC
# MAGIC We need to convert the PDF documents bytes to text, and extract chunks from their content.
# MAGIC
# MAGIC This part can be tricky as PDFs are hard to work with and can be saved as images, for which we'll need an OCR to extract the text.
# MAGIC
# MAGIC Using the `Unstructured` library within a Spark UDF makes it easy to extract text. 
# MAGIC
# MAGIC *Note: Your cluster will need a few extra libraries that you would typically install with a cluster init script.*
# MAGIC
# MAGIC <br style="clear: both">
# MAGIC
# MAGIC ### Splitting our big documentation page in smaller chunks
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/chunk-window-size.png?raw=true" style="float: right" width="700px">
# MAGIC
# MAGIC In this demo, some PDFs are very large, with a lot of text.
# MAGIC
# MAGIC We'll extract the content and then use llama_index `SentenceSplitter`, and ensure that each chunk isn't bigger than 500 tokens. 
# MAGIC
# MAGIC
# MAGIC The chunk size and chunk overlap depend on the use case and the PDF files. 
# MAGIC
# MAGIC Remember that your prompt+answer should stay below your model max window size (4096 for llama2). 
# MAGIC
# MAGIC For more details, review the previous [../01-Data-Preparation](01-Data-Preparation) notebook. 
# MAGIC
# MAGIC <br/>
# MAGIC <br style="clear: both">
# MAGIC <div style="background-color: #def2ff; padding: 15px;  border-radius: 30px; ">
# MAGIC   <strong>Information</strong><br/>
# MAGIC   Remember that the following steps are specific to your dataset. This is a critical part to building a successful RAG assistant.
# MAGIC   <br/> Always take time to review the chunks created and ensure they make sense and contain relevant information.
# MAGIC </div>

# COMMAND ----------

#chunking function

from pyspark.sql.functions import pandas_udf
from llama_index.langchain_helpers.text_splitter import SentenceSplitter
from llama_index import Document, set_global_tokenizer
from transformers import AutoTokenizer
from typing import Iterator
from langchain.text_splitter import RecursiveCharacterTextSplitter
import pandas as pd

import nltk
nltk.download('punkt')

# Reduce the arrow batch size as our PDF can be big in memory
spark.conf.set("spark.sql.execution.arrow.maxRecordsPerBatch", 10)

@pandas_udf("array<string>")
def read_as_chunk(batch_iter: Iterator[pd.Series]) -> Iterator[pd.Series]:
    #set llama2 as tokenizer to match our model size (will stay below BGE 1024 limit)
    set_global_tokenizer(
      AutoTokenizer.from_pretrained("hf-internal-testing/llama-tokenizer")
    )
    #Sentence splitter from llama_index to split on sentences
    splitter = SentenceSplitter(chunk_size=500, chunk_overlap=25)
    def extract_and_split(b):
      txt = extract_doc_text(b)
      nodes = splitter.get_nodes_from_documents([Document(text=txt)])
      return [n.text for n in nodes]

    for x in batch_iter:
        yield x.apply(extract_and_split)

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC ## What's required for our Vector Search Index
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/databricks-vector-search-type.png?raw=true" style="float: right" width="800px">
# MAGIC
# MAGIC Databricks provide multiple types of vector search indexes:
# MAGIC
# MAGIC - **Managed embeddings**: you provide a text column and endpoint name and Databricks synchronizes the index with your Delta table 
# MAGIC - **Self Managed embeddings**: you compute the embeddings and save them as a field of your Delta Table, Databricks will then synchronize the index
# MAGIC - **Direct index**: when you want to use and update the index without having a Delta Table.
# MAGIC
# MAGIC In this demo, we will show you how to setup a **Self-managed Embeddings** index. 
# MAGIC
# MAGIC To do so, we will have to first compute the embeddings of our chunks and save them as a Delta Lake table field as `array&ltfloat&gt`

# COMMAND ----------

# MAGIC %md
# MAGIC ###BGE Embedding Endpoint

# COMMAND ----------

#embedding

from mlflow.deployments import get_deploy_client

# bge-large-en Foundation models are available using the /serving-endpoints/databricks-bge-large-en/invocations api. 
deploy_client = get_deploy_client("databricks")

## NOTE: if you change your embedding model here, make sure you change it in the query step too
bge_embeddings = deploy_client.predict(endpoint="databricks-bge-large-en", inputs={"input": ["What is Apache Spark?"]})

# COMMAND ----------

# MAGIC %md
# MAGIC ###Ada Embedding Endpoint

# COMMAND ----------

from langchain_community.chat_models import ChatDatabricks
from langchain_core.messages import HumanMessage
from mlflow.deployments import get_deploy_client

# create endpoint for ada-002 model

client = get_deploy_client("databricks")

name = "text-embedding-ada-002"
try:
  client.create_endpoint(
    name=name,
    config={
      "served_entities": [
        {
          "name": name,
          "external_model": {
            "name": name,
            "provider": "openai",
            "task": "llm/v1/embeddings",
              "openai_config": {
            "openai_api_key": "{{secrets/my_openai_secret_scope/openai_api_key}}"
            }
          },
        }
      ],
    },
  )
except Exception as e:
  if 'RESOURCE_ALREADY_EXISTS' in str(e):
    print('Endpoint already exists')
  else:
    print(e)

ada_embedding = client.predict(endpoint="text-embedding-ada-002", inputs={"input": ["What is Apache Spark?"]})

# COMMAND ----------

# MAGIC %md
# MAGIC ###Openai Large Embedding Endpoint

# COMMAND ----------

from langchain_community.chat_models import ChatDatabricks
from langchain_core.messages import HumanMessage
from mlflow.deployments import get_deploy_client

# create endpoint for ada-002 model

client = get_deploy_client("databricks")

name = "text-embedding-3-large"
try:
  client.create_endpoint(
    name=name,
    config={
      "served_entities": [
        {
          "name": name,
          "external_model": {
            "name": name,
            "provider": "openai",
            "task": "llm/v1/embeddings",
              "openai_config": {
            "openai_api_key": "{{secrets/my_openai_secret_scope/openai_api_key}}"
            }
          },
        }
      ],
    },
  )
except Exception as e:
  if 'RESOURCE_ALREADY_EXISTS' in str(e):
    print('Endpoint already exists')
  else:
    print(e)

openai_large_embedding = client.predict(endpoint=name, inputs={"input": ["What is Apache Spark?"]})

# COMMAND ----------

#embedding functions

@pandas_udf("array<float>")
def get_bge_embedding(contents: pd.Series) -> pd.Series:
    import mlflow.deployments
    
    deploy_client = mlflow.deployments.get_deploy_client("databricks")
    
    def get_embeddings(batch):
        try:
            response = deploy_client.predict(endpoint="databricks-bge-large-en", inputs={"input": batch})
            return [e['embedding'] for e in response.data]
        except Exception as e:
            print(f"Error while getting embeddings: {str(e)}")
            return [None] * len(batch)
    
    # Splitting the contents into batches of 150 items each, since the embedding model takes at most 150 inputs per request.
    max_batch_size = 150
    batches = [contents.iloc[i:i + max_batch_size] for i in range(0, len(contents), max_batch_size)]
    
    # Process each batch and collect the results
    all_embeddings = []
    for batch in batches:
        all_embeddings += get_embeddings(batch.tolist())
    
    return pd.Series(all_embeddings)

# ---------

@pandas_udf("array<float>")
def get_ada_embedding(contents: pd.Series) -> pd.Series:
    import mlflow.deployments
    
    deploy_client = mlflow.deployments.get_deploy_client("databricks")
    
    def get_embeddings(batch):
        try:
            response = deploy_client.predict(endpoint="text-embedding-ada-002", inputs={"input": batch})
            return [e['embedding'] for e in response.data]
        except Exception as e:
            print(f"Error while getting embeddings: {str(e)}")
            return [None] * len(batch)
    
    # Splitting the contents into batches of 150 items each, since the embedding model takes at most 150 inputs per request.
    max_batch_size = 150
    batches = [contents.iloc[i:i + max_batch_size] for i in range(0, len(contents), max_batch_size)]
    
    # Process each batch and collect the results
    all_embeddings = []
    for batch in batches:
        all_embeddings += get_embeddings(batch.tolist())
    
    return pd.Series(all_embeddings)

# ---------

@pandas_udf("array<float>")
def get_openai_large_embedding(contents: pd.Series) -> pd.Series:
    import mlflow.deployments
    
    deploy_client = mlflow.deployments.get_deploy_client("databricks")
    
    def get_embeddings(batch):
        try:
            response = deploy_client.predict(endpoint="text-embedding-3-large", inputs={"input": batch})
            return [e['embedding'] for e in response.data]
        except Exception as e:
            print(f"Error while getting embeddings: {str(e)}")
            return [None] * len(batch)
    
    # Splitting the contents into batches of 150 items each, since the embedding model takes at most 150 inputs per request.
    max_batch_size = 150
    batches = [contents.iloc[i:i + max_batch_size] for i in range(0, len(contents), max_batch_size)]
    
    # Process each batch and collect the results
    all_embeddings = []
    for batch in batches:
        all_embeddings += get_embeddings(batch.tolist())
    
    return pd.Series(all_embeddings)

# COMMAND ----------

from pyspark.sql.functions import explode
import json
from azure.identity import ManagedIdentityCredential
from azure.storage.queue import QueueClient
import base64
import time
import unstructured
import os
import traceback

volume_location = "/Volumes/main/rag_chatbot_callum_elder/armhub_experimental"

for file_name in os.listdir(volume_location):
    if file_name.endswith(".pdf"):
        file_path = os.path.join(volume_location, file_name)
        print("Processing file:", file_path)
        
        try:
            with open(file_path, 'rb') as file:
                pdf_content = file.read()
                basename = file_name.rsplit('.', 1)[0]
                pdf_df = spark.createDataFrame([(file_path, basename, pdf_content)], ["url", "basename", "content"])
                chunked_df = pdf_df.select("url", "basename", read_as_chunk("content").alias("chunks"))
                exploded_df = chunked_df.select("url", "basename", explode("chunks").alias("content"))
                embedded_df = exploded_df.select("url", "basename", "content", get_bge_embedding("content").alias("bge_embedding"), get_ada_embedding("content").alias("ada_embedding"), get_openai_large_embedding("content").alias("openai_large_embedding"))
                delta_table_path = "main.rag_chatbot_callum_elder.500_25_experimental"
                embedded_df.write.format("delta").option("mergeSchema", "true").mode("append").saveAsTable(delta_table_path)
                print("Chunking, embedding, and saving to Delta table completed for file:", file_path)
        except Exception as e:
            print(f"An error occurred while processing the file {file_path}: {str(e)}")
            print("Traceback:")
            traceback.print_exc()
        
        print("---")

# COMMAND ----------

# MAGIC %md 
# MAGIC Let's start by extracting text from our PDF.

# COMMAND ----------

# MAGIC %md
# MAGIC This looks great. We'll now wrap it with a text_splitter to avoid having too big pages, and create a Pandas UDF function to easily scale that across multiple nodes.
# MAGIC
# MAGIC *Note that our pdf text isn't clean. To make it nicer, we could use a few extra LLM-based pre-processing steps, asking to remove unrelevant content like the list of chapters and to only keep the core text.*

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC ## Introducing Databricks BGE Embeddings Foundation Model endpoints
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/rag-pdf-self-managed-4.png?raw=true" style="float: right; width: 600px; margin-left: 10px">
# MAGIC
# MAGIC Foundation Models are provided by Databricks, and can be used out-of-the-box.
# MAGIC
# MAGIC Databricks supports several endpoint types to compute embeddings or evaluate a model:
# MAGIC - A **foundation model endpoint**, provided by databricks (ex: llama2-70B, MPT...)
# MAGIC - An **external endpoint**, acting as a gateway to an external model (ex: Azure OpenAI)
# MAGIC - A **custom**, fined-tuned model hosted on Databricks model service
# MAGIC
# MAGIC Open the [Model Serving Endpoint page](/ml/endpoints) to explore and try the foundation models.
# MAGIC
# MAGIC For this demo, we will use the foundation model `BGE` (embeddings) and `llama2-70B` (chat). <br/><br/>
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/databricks-foundation-models.png?raw=true" width="600px" >

# COMMAND ----------

# MAGIC %md
# MAGIC ### Computing the chunk embeddings and saving them to our Delta Table
# MAGIC
# MAGIC The last step is to now compute an embedding for all our documentation chunks. Let's create an udf to compute the embeddings using the foundation model endpoint.
# MAGIC
# MAGIC *Note that this part would typically be setup as a production-grade job, running as soon as a new documentation page is updated. <br/> This could be setup as a Delta Live Table pipeline to incrementally consume updates.*

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC
# MAGIC ### Our dataset is now ready! Let's create our Self-Managed Vector Search Index.
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/chatbot-rag/rag-pdf-self-managed-3.png?raw=true" style="float: right; width: 600px; margin-left: 10px">
# MAGIC
# MAGIC Our dataset is now ready. We chunked the documentation pages into small sections, computed the embeddings and saved it as a Delta Lake table.
# MAGIC
# MAGIC Next, we'll configure Databricks Vector Search to ingest data from this table.
# MAGIC
# MAGIC Vector search index uses a Vector search endpoint to serve the embeddings (you can think about it as your Vector Search API endpoint). <br/>
# MAGIC Multiple Indexes can use the same endpoint. Let's start by creating one.

# COMMAND ----------

# DBTITLE 1,Creating the Vector Search endpoint
from databricks.vector_search.client import VectorSearchClient
vsc = VectorSearchClient()

VECTOR_SEARCH_ENDPOINT_NAME = "500_25_experimental_vector_search"

if not endpoint_exists(vsc, VECTOR_SEARCH_ENDPOINT_NAME):
    vsc.create_endpoint(name=VECTOR_SEARCH_ENDPOINT_NAME, endpoint_type="STANDARD")

wait_for_vs_endpoint_to_be_ready(vsc, VECTOR_SEARCH_ENDPOINT_NAME)
print(f"Endpoint named {VECTOR_SEARCH_ENDPOINT_NAME} is ready.")

# COMMAND ----------

# MAGIC %md 
# MAGIC
# MAGIC You can view your endpoint on the [Vector Search Endpoints UI](#/setting/clusters/vector-search). Click on the endpoint name to see all indexes that are served by the endpoint.

# COMMAND ----------

# MAGIC %md
# MAGIC ##BGE Index

# COMMAND ----------

# DBTITLE 1,Create the Self-managed vector search using our endpoint
from databricks.sdk import WorkspaceClient
import databricks.sdk.service.catalog as c

#The table we'd like to index
source_table_fullname = "main.rag_chatbot_callum_elder.500_25_experimental"
# Where we want to store our index
vs_index_fullname = "main.rag_chatbot_callum_elder.500_25_experimental_bge_self_managed_vs_index"

if not index_exists(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname):
  print(f"Creating index {vs_index_fullname} on endpoint {VECTOR_SEARCH_ENDPOINT_NAME}...")
  vsc.create_delta_sync_index(
    endpoint_name=VECTOR_SEARCH_ENDPOINT_NAME,
    index_name=vs_index_fullname,
    source_table_name=source_table_fullname,
    pipeline_type="TRIGGERED", #Sync needs to be manually triggered
    primary_key="id",
    embedding_dimension=1024, #Match your model embedding size (bge)
    embedding_vector_column="bge_embedding"
  )
else:
  #Trigger a sync to update our vs content with the new data saved in the table
  vsc.get_index(VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname).sync()

#Let's wait for the index to be ready and all our embeddings to be created and indexed
wait_for_index_to_be_ready(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname)

# COMMAND ----------

# MAGIC %md
# MAGIC ###Ada index

# COMMAND ----------

from databricks.sdk import WorkspaceClient
import databricks.sdk.service.catalog as c

#The table we'd like to index
source_table_fullname = "main.rag_chatbot_callum_elder.500_25_experimental"
# Where we want to store our index
vs_index_fullname = "main.rag_chatbot_callum_elder.500_25_experimental_ada_self_managed_vs_index"

if not index_exists(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname):
  print(f"Creating index {vs_index_fullname} on endpoint {VECTOR_SEARCH_ENDPOINT_NAME}...")
  vsc.create_delta_sync_index(
    endpoint_name=VECTOR_SEARCH_ENDPOINT_NAME,
    index_name=vs_index_fullname,
    source_table_name=source_table_fullname,
    pipeline_type="TRIGGERED", #Sync needs to be manually triggered
    primary_key="id",
    embedding_dimension=1536, #ada
    embedding_vector_column="ada_embedding"
  )
else:
  #Trigger a sync to update our vs content with the new data saved in the table
  vsc.get_index(VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname).sync()

#Let's wait for the index to be ready and all our embeddings to be created and indexed
wait_for_index_to_be_ready(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname)

# COMMAND ----------

# MAGIC %md
# MAGIC ###Openai Large Index

# COMMAND ----------

from databricks.sdk import WorkspaceClient
import databricks.sdk.service.catalog as c

#The table we'd like to index
source_table_fullname = "main.rag_chatbot_callum_elder.500_25_experimental"
# Where we want to store our index
vs_index_fullname = "main.rag_chatbot_callum_elder.500_25_experimental_openai_large_self_managed_vs_index"

if not index_exists(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname):
  print(f"Creating index {vs_index_fullname} on endpoint {VECTOR_SEARCH_ENDPOINT_NAME}...")
  vsc.create_delta_sync_index(
    endpoint_name=VECTOR_SEARCH_ENDPOINT_NAME,
    index_name=vs_index_fullname,
    source_table_name=source_table_fullname,
    pipeline_type="TRIGGERED", #Sync needs to be manually triggered
    primary_key="id",
    embedding_dimension=3072, #ada
    embedding_vector_column="openai_large_embedding"
  )
else:
  #Trigger a sync to update our vs content with the new data saved in the table
  vsc.get_index(VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname).sync()

#Let's wait for the index to be ready and all our embeddings to be created and indexed
wait_for_index_to_be_ready(vsc, VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname)

# COMMAND ----------

# MAGIC %md 
# MAGIC ## Searching for similar content
# MAGIC
# MAGIC That's all we have to do. Databricks will automatically capture and synchronize new entries in your Delta Lake Table.
# MAGIC
# MAGIC Note that depending on your dataset size and model size, index creation can take a few seconds to start and index your embeddings.
# MAGIC
# MAGIC Let's give it a try and search for similar content.
# MAGIC
# MAGIC *Note: `similarity_search` also supports a filters parameter. This is useful to add a security layer to your RAG system: you can filter out some sensitive content based on who is doing the call (for example filter on a specific department based on the user preference).*

# COMMAND ----------

question = "Can you tell me about recent armhub projects?"

response = deploy_client.predict(endpoint="databricks-bge-large-en", inputs={"input": [question]})
embeddings = [e['embedding'] for e in response.data]

results = vsc.get_index(VECTOR_SEARCH_ENDPOINT_NAME, vs_index_fullname).similarity_search(
  query_vector=embeddings[0],
  columns=["url", "content"],
  num_results=1)
docs = results.get('result', {}).get('data_array', [])
pprint(docs)

# COMMAND ----------

# MAGIC %md 
# MAGIC ## Next step: Deploy our chatbot model with RAG
# MAGIC
# MAGIC We've seen how Databricks Lakehouse AI makes it easy to ingest and prepare your documents, and deploy a Self Managed Vector Search index on top of it with just a few lines of code and configuration.
# MAGIC
# MAGIC This simplifies and accelerates your data projects so that you can focus on the next step: creating your realtime chatbot endpoint with well-crafted prompt augmentation.
# MAGIC
# MAGIC Open the [02-Advanced-Chatbot-Chain]($./02-Advanced-Chatbot-Chain) notebook to create and deploy a chatbot endpoint.
